#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

// BLE provisioning formats:
//   SERVER|SMS_HUB_HOST
//   MQTT|MQTT_BROKER|MQTT_USER|MQTT_PASS
//   SSID|PASSWORD|MQTT_BROKER|MQTT_USER|MQTT_PASS

#endif
